# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default=b'No description available', max_length=250),
        ),
    ]
